language: python

python:
  - "2.7"

sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install ntp

script:
  - travis_run_tests	

notifications:
  webhooks: http://104.236.200.16:8002/